version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    container_name: convo_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: convo
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - convo

volumes:
  db_data:

networks:
  convo:
    driver: bridge